name: ci

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            preset: msvc-vs2022-debug
          - os: ubuntu-latest
            preset: ninja-clang-debug
          - os: ubuntu-latest
            preset: ninja-gcc-debug
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}
      - name: Test
        run: ctest --preset ${{ matrix.preset }}
